const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
document.addEventListener('DOMContentLoaded', () => {
  const advanced = document.createElement('details');
  advanced.className = 'advanced-analysis';
  advanced.innerHTML = '<summary>Advanced analysis: stress tests, evidence and review</summary><div></div>';
  const stress = document.querySelector('#stress');
  stress.before(advanced);
  const content = advanced.lastElementChild;
  let section = advanced.nextElementSibling;
  while (section && !section.classList.contains('export')) {
    const next = section.nextElementSibling;
    content.append(section);
    section = next;
  }
  document.querySelectorAll('.top nav a[href^="#"]').forEach(a => a.addEventListener('click', () => {
    const target = document.querySelector(a.getAttribute('href'));
    if (target && advanced.contains(target)) advanced.open = true;
  }));
});
const N=v=>Number(v)||0,M=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n||0);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let last=null,lastCounter="";

function input(){
  const o=Object.fromEntries(new FormData($("#decisionForm")).entries());
  ["cargo_qty","freight_rate","target_tce","distance","speed","sea_cons","port_days","bunker_price","daily_hire","port_costs","canal_costs","commission","laycan_buffer","delay_cost","weather_risk","current_risk","wave_height","eu_share"].forEach(k=>o[k]=N(o[k]));
  o.evidence_docs=$$("#evidenceChecks input:checked").map(x=>x.value);
  return o;
}

function estimate(v,speed=v.speed,consDelta=0,delay=0,overrides={}){
  const q={...v,...overrides},effectiveSpeed=Math.max(6,speed),sea=q.distance/(effectiveSpeed*24),days=sea+q.port_days+delay;
  const tons=sea*q.sea_cons*(1+consDelta)+q.port_days*4,bunker=tons*q.bunker_price,gross=q.cargo_qty*q.freight_rate;
  const commission=gross*q.commission/100,laycanOver=Math.max(0,delay-q.laycan_buffer),delayExposure=laycanOver*q.delay_cost;
  const costs=bunker+q.port_costs+q.canal_costs+days*q.daily_hire+commission+delayExposure,net=gross-costs;
  return{voyage_days:+days.toFixed(2),sea_days:+sea.toFixed(2),fuel_tons:+tons.toFixed(1),bunker_cost:Math.round(bunker),commission_cost:Math.round(commission),hire_cost:Math.round(days*q.daily_hire),delay_exposure:Math.round(delayExposure),total_cost:Math.round(costs),net_profit:Math.round(net),tce:Math.round((net+days*q.daily_hire)/Math.max(days,1)),daily_profit:Math.round(net/Math.max(days,1)),gross_revenue:Math.round(gross)};
}

function stressCases(v,baseDelay,speedLoss){
  const speed=Math.max(6,v.speed-speedLoss),make=(name,changes,delay=baseDelay)=>({name,changes,...estimate(v,speed,0,delay,changes)});
  return[make("Expected",{}),make("Bunker +15%",{bunker_price:v.bunker_price*1.15}),make("Freight -7.5%",{freight_rate:v.freight_rate*.925}),make("Port delay +3d",{},baseDelay+3),make("Port costs +25%",{port_costs:v.port_costs*1.25}),make("Compound downside",{bunker_price:v.bunker_price*1.15,freight_rate:v.freight_rate*.925,port_costs:v.port_costs*1.2},baseDelay+2.5)];
}

function model(v){
  const delay=+(v.weather_risk*.024+Math.max(0,v.wave_height-2)*.22).toFixed(2),loss=Math.min(3.5,v.weather_risk*.018+v.current_risk*.01+Math.max(0,v.wave_height-1.5)*.24);
  const specs=[["Slow steam",Math.max(8,v.speed-1.8),-.18,delay+.65],["Economy",Math.max(8,v.speed-1),-.11,delay+.3],["Base",v.speed,0,delay],["Schedule protection",Math.min(18,v.speed+1),.14,Math.max(0,delay-.45)],["Weather guard",Math.max(8,v.speed-.3),.06,Math.max(0,delay-.75)]];
  const replay=specs.map(([name,s,d,h])=>({name,speed:+s.toFixed(1),effective_speed:+Math.max(6,s-loss).toFixed(1),weather_delay_days:+h.toFixed(2),...estimate(v,s-loss,d,h)}));
  const viable=replay.filter(x=>x.tce>=v.target_tce),best=(viable.length?viable:replay).reduce((a,b)=>b.net_profit>a.net_profit?b:a);
  const docs=["fixture recap","charter party","nor","sof","port log","invoice"],items=docs.map(document=>({document,ready:v.evidence_docs.includes(document)}));
  const evidence=Math.round(items.filter(x=>x.ready).length/docs.length*100),ocean=Math.min(100,Math.round(v.weather_risk*.45+v.current_risk*.25+v.wave_height*5.5));
  const base=replay[2],targetGap=v.target_tce-base.tce,commercial=Math.max(5,Math.min(95,48+Math.max(0,targetGap)/650+Math.max(0,-base.net_profit)/18000+delay*5));
  const laycanRisk=Math.min(100,Math.round(Math.max(0,delay-v.laycan_buffer)*26+v.weather_risk*.28)),appetite={conservative:8,balanced:0,commercial:-7}[v.risk_appetite]||0;
  const risk=Math.round(Math.max(0,Math.min(100,commercial*.34+ocean*.23+(100-evidence)*.19+laycanRisk*.24+appetite)));
  const co2=Math.round(base.fuel_tons*3.114),carbon=Math.min(100,Math.round(18+v.eu_share*.42)),stresses=stressCases(v,delay,loss),compound=stresses.at(-1),positiveCases=stresses.filter(x=>x.net_profit>0).length;
  const variableCost=base.total_cost-base.commission_cost,breakEvenFreight=variableCost/(Math.max(v.cargo_qty,1)*(1-v.commission/100)),requiredFreight=(variableCost-base.hire_cost+v.target_tce*base.voyage_days)/(Math.max(v.cargo_qty,1)*(1-v.commission/100));
  const confidence=Math.max(18,Math.min(96,Math.round(evidence*.62+(100-Math.min(100,ocean))*.18+70*.2)));
  const gates=[{label:"Commercial target",pass:base.tce>=v.target_tce,detail:`TCE ${M(base.tce)} vs target ${M(v.target_tce)}`},{label:"Downside resilience",pass:compound.net_profit>0,detail:`Compound case ${M(compound.net_profit)}`},{label:"Laycan protection",pass:delay<=v.laycan_buffer,detail:`Expected delay ${delay}d / buffer ${v.laycan_buffer}d`},{label:"Evidence completeness",pass:evidence>=67,detail:`${evidence}% core documents ready`},{label:"Ocean exposure",pass:ocean<65,detail:`Ocean risk ${ocean}/100`}];
  const failed=gates.filter(x=>!x.pass).length,decision=risk>=72||failed>=4?"AVOID / SENIOR REVIEW":risk>=48||failed>=2?"WATCH / COUNTER":"FIX WITH GUARDS";
  const counterRate=Math.max(v.freight_rate,requiredFreight),counterDemurrage=Math.max(v.delay_cost,Math.round(v.daily_hire*1.08/500)*500);
  const counter=`Owners counter basis ${v.vessel_name}, ${v.cargo_type} ${v.cargo_qty.toLocaleString("en-US")} mt, ${v.route}, freight USD ${counterRate.toFixed(2)} per unit, demurrage USD ${counterDemurrage.toLocaleString("en-US")} pdpr, laycan buffer minimum ${Math.max(2,v.laycan_buffer).toFixed(1)} days, otherwise as per clean recap and mutually agreed CP terms.`;
  const sensitivity=[{label:"Freight -5%",impact:estimate(v,Math.max(6,v.speed-loss),0,delay,{freight_rate:v.freight_rate*.95}).net_profit-base.net_profit},{label:"Bunker +15%",impact:estimate(v,Math.max(6,v.speed-loss),0,delay,{bunker_price:v.bunker_price*1.15}).net_profit-base.net_profit},{label:"Delay +2 days",impact:estimate(v,Math.max(6,v.speed-loss),0,delay+2).net_profit-base.net_profit},{label:"Port costs +20%",impact:estimate(v,Math.max(6,v.speed-loss),0,delay,{port_costs:v.port_costs*1.2}).net_profit-base.net_profit},{label:"Freight +5%",impact:estimate(v,Math.max(6,v.speed-loss),0,delay,{freight_rate:v.freight_rate*1.05}).net_profit-base.net_profit}];
  return{decision,risk_score:risk,confidence,approval_status:risk>=72||evidence<50?"Blocked":"Reviewer required",digital_twin:{effective_speed:+Math.max(6,v.speed-loss).toFixed(1),speed_loss:+loss.toFixed(1),weather_delay_days:delay,base},decision_replay:replay,recommended_scenario:best.name,ocean_risk:{score:ocean,wave_height:v.wave_height,source:"user input / Copernicus-ready"},carbon:{co2_tons:co2,ets_cost_eur:Math.round(co2*v.eu_share/100*.7*72),fueleu_risk:carbon},evidence_chain:{score:evidence,items},boundaries:{break_even_freight:breakEvenFreight,required_freight:requiredFreight,target_gap:targetGap,positive_cases:positiveCases,total_cases:stresses.length,compound_net:compound.net_profit},stress_cases:stresses,sensitivity,gates,counter,counter_rate:counterRate,explanations:[["Commercial",Math.round(commercial),"TCE gap, P&L, bunker and time cost."],["Ocean",ocean,"Weather, current and wave assumptions."],["Laycan",laycanRisk,`Delay compared with ${v.laycan_buffer} day buffer.`],["Evidence",100-evidence,`${evidence}% core documents ready.`],["Carbon",carbon,"EU ETS and FuelEU screening."]].map(x=>({factor:x[0],score:x[1],reason:x[2]})),actions:[failed?`Clear ${failed} failed decision gate${failed>1?"s":""} before fixing.`:"All primary gates clear; preserve assumptions in the recap.",`Counter at or above USD ${counterRate.toFixed(2)} to defend target TCE.`,`Use ${best.name} as the preferred operating posture, subject to laycan verification.`,"Attach missing evidence and record reviewer conditions."],source:"frontend transparent decision model"};
}

function metric(a,b,c=""){return`<article class="metric"><span>${esc(a)}</span><b>${esc(b)}</b><small>${esc(c)}</small></article>`}
function render(r,mode){
  last=r;lastCounter=r.counter;const v=input(),t=r.digital_twin,b=t.base;
  $("#decisionStatus").textContent=r.decision;$("#riskStatus").textContent=r.risk_score+" / 100";$("#approvalStatus").textContent=r.approval_status;$("#engineMode").textContent=mode;$("#confidenceBar").style.width=r.confidence+"%";$("#confidenceText").textContent=`Model confidence ${r.confidence}%`;$("#shipMarker").style.left=Math.max(12,Math.min(88,100-r.risk_score))+"%";
  $("#twinMetrics").innerHTML=metric("Effective speed",t.effective_speed+" kn","loss "+t.speed_loss)+metric("Voyage",b.voyage_days+" days","weather +"+t.weather_delay_days)+metric("TCE",M(b.tce)+"/day",`target ${M(v.target_tce)}`)+metric("Net result",M(b.net_profit),`${b.fuel_tons} t fuel`);
  $("#recommendedScenario").textContent="Recommended: "+r.recommended_scenario;$("#scenarioGrid").innerHTML=r.decision_replay.map(x=>`<article class="scenario ${x.name===r.recommended_scenario?"best":""}"><p class="eye">${esc(x.name)}</p><h3>${M(x.net_profit)}</h3><dl><dt>Effective speed</dt><dd>${x.effective_speed} kn</dd><dt>Voyage</dt><dd>${x.voyage_days} d</dd><dt>TCE</dt><dd>${M(x.tce)}</dd><dt>Bunker</dt><dd>${M(x.bunker_cost)}</dd></dl></article>`).join("");
  $("#boundaryMetrics").innerHTML=metric("Break-even freight","USD "+r.boundaries.break_even_freight.toFixed(2),"zero voyage result")+metric("Target-TCE freight","USD "+r.boundaries.required_freight.toFixed(2),`${M(v.target_tce)}/day target`)+metric("Target gap",M(r.boundaries.target_gap),r.boundaries.target_gap<=0?"target achieved":"per day below target")+metric("Resilience",`${r.boundaries.positive_cases}/${r.boundaries.total_cases} cases`,`compound ${M(r.boundaries.compound_net)}`);
  $("#stressTable").innerHTML=r.stress_cases.map(x=>`<article><span>${esc(x.name)}</span><b class="${x.net_profit>=0?"ok":"bad"}">${M(x.net_profit)}</b><small>TCE ${M(x.tce)} · ${x.voyage_days}d</small></article>`).join("");const max=Math.max(...r.sensitivity.map(x=>Math.abs(x.impact)),1);$("#sensitivityChart").innerHTML=r.sensitivity.map(x=>`<article><span>${esc(x.label)}</span><div><i class="${x.impact>=0?"up":"down"}" style="width:${Math.max(4,Math.abs(x.impact)/max*100)}%"></i></div><b class="${x.impact>=0?"ok":"bad"}">${x.impact>=0?"+":""}${M(x.impact)}</b></article>`).join("");
  $("#counterStrategy").innerHTML=`<span>Defended counter rate</span><strong>USD ${r.counter_rate.toFixed(2)}</strong><p>${esc(r.counter)}</p>`;$("#counterBadge").textContent=r.counter_rate>v.freight_rate?"counter required":"offer defensible";const clear=r.gates.filter(x=>x.pass).length;$("#gateProgress").textContent=`${clear} / ${r.gates.length} clear`;$("#decisionGates").innerHTML=r.gates.map(x=>`<article class="${x.pass?"pass":"fail"}"><i>${x.pass?"✓":"!"}</i><div><b>${esc(x.label)}</b><span>${esc(x.detail)}</span></div></article>`).join("");
  $("#oceanMetrics").innerHTML=metric("Ocean risk",r.ocean_risk.score+"/100",r.ocean_risk.source)+metric("Wave",r.ocean_risk.wave_height+" m","user input")+metric("CO2",r.carbon.co2_tons+" t","screening")+metric("EU ETS","EUR "+r.carbon.ets_cost_eur,"planning");$("#evidenceScore").textContent=r.evidence_chain.score+"% ready";$("#evidenceLedger").innerHTML=r.evidence_chain.items.map(x=>`<div class="ledger"><span>${esc(x.document)}</span><b class="${x.ready?"ok":"bad"}">${x.ready?"Ready":"Missing"}</b></div>`).join("");$("#factorList").innerHTML=r.explanations.map(x=>`<article class="factor"><b>${esc(x.factor)}</b><strong>${x.score}/100</strong><span>${esc(x.reason)}</span><meter min="0" max="100" value="${x.score}"></meter></article>`).join("");$("#actionList").innerHTML=r.actions.map(x=>`<li>${esc(x)}</li>`).join("");$("#gateStatus").textContent=r.approval_status;localStorage.setItem("focuseaDecisionLabLast",JSON.stringify({input:v,result:r,time:new Date().toISOString()}));
}

async function run(e){e?.preventDefault();const v=input(),result=model(v);let mode="Local planning model";if(v.api_base)try{const q=await fetch(v.api_base.replace(/\/$/,"")+"/api/decision-lab/evaluate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(v),signal:AbortSignal.timeout(8000)});if(!q.ok)throw Error();await q.json();mode="Local model · backend reachable"}catch{mode="Local model · backend unavailable"}render(result,mode)}

const presets={dry:{cargo_type:"coal",cargo_qty:50000,freight_rate:18.5,target_tce:22000,distance:5800,speed:13,sea_cons:28,port_days:5,bunker_price:686.5,daily_hire:14500,port_costs:68000,canal_costs:0,commission:2.5,laycan_buffer:3,delay_cost:12000,weather_risk:32,current_risk:20,wave_height:2.1,eu_share:50,route:"Tanjung Bara → Paradip"},tanker:{cargo_type:"crudeOil",cargo_qty:80000,freight_rate:26,target_tce:32000,distance:6400,speed:12.5,sea_cons:34,port_days:4,bunker_price:690,daily_hire:23000,port_costs:112000,canal_costs:0,commission:2.5,laycan_buffer:2,delay_cost:24000,weather_risk:28,current_risk:18,wave_height:1.8,eu_share:35,route:"Ras Tanura → Rotterdam"},container:{cargo_type:"container",cargo_qty:2200,freight_rate:620,target_tce:26000,distance:7100,speed:16,sea_cons:42,port_days:4,bunker_price:705,daily_hire:19500,port_costs:145000,canal_costs:420000,commission:1.25,laycan_buffer:1.5,delay_cost:30000,weather_risk:35,current_risk:24,wave_height:2.4,eu_share:60,route:"Shanghai → Rotterdam"},distressed:{cargo_type:"grain",cargo_qty:42000,freight_rate:16,target_tce:21000,distance:6500,speed:12,sea_cons:29,port_days:8,bunker_price:760,daily_hire:17000,port_costs:118000,canal_costs:0,commission:3.75,laycan_buffer:1,delay_cost:18000,weather_risk:74,current_risk:55,wave_height:4.2,eu_share:50,route:"Santos → Alexandria"}};
$$('[data-preset]').forEach(button=>button.onclick=()=>{const f=$("#decisionForm"),p=presets[button.dataset.preset];Object.entries(p).forEach(([k,v])=>{const el=f.elements[k];if(el){el.value=v;if(el.type==="range")el.nextElementSibling.textContent=v+"%"}});$$('[data-preset]').forEach(x=>x.classList.add("ghost"));button.classList.remove("ghost");run()});$("#decisionForm").addEventListener("submit",run);$("#decisionForm").addEventListener("input",e=>{if(e.target.type==="range")e.target.nextElementSibling.textContent=e.target.value+"%"});$("#evidenceChecks").addEventListener("change",run);

const get=k=>{try{return JSON.parse(localStorage.getItem(k)||"[]")}catch{return[]}},put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function showAudit(){const a=get("focuseaDecisionApprovals");$("#auditList").innerHTML=a.length?a.slice(0,6).map(x=>`<div class="audit"><b>${esc(x.status)}</b><span>${esc(x.reviewer)} · ${new Date(x.time).toLocaleString()}</span><p>${esc(x.note)}</p></div>`).join(""):"<p>No approval event yet.</p>"}
$$('[data-approval]').forEach(b=>b.onclick=()=>{const f=new FormData($("#approvalForm")),reviewer=String(f.get("reviewer")||"").trim(),status=b.dataset.approval;if(!reviewer)return alert("Reviewer name is required.");if(status==="Approved"&&(!last||last.approval_status==="Blocked"))return alert("Approval is blocked until risk and evidence gates are cleared.");const a=get("focuseaDecisionApprovals");a.unshift({status,reviewer,note:String(f.get("note")||"No note"),risk:last?.risk_score,time:new Date().toISOString()});put("focuseaDecisionApprovals",a.slice(0,50));$("#gateStatus").textContent=status;showAudit()});
function median(a){a=a.filter(Boolean).sort((x,y)=>x-y);if(!a.length)return 0;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}function showBench(){const r=get("focuseaAnonymousBenchmarks"),fixed=r.filter(x=>x.result==="Fixed").length;$("#benchmarkMetrics").innerHTML=metric("Sample",r.length,"browser workspace")+metric("Median TCE",M(median(r.map(x=>x.tce))),"private")+metric("Median freight",median(r.map(x=>x.freight)).toFixed(2))+metric("Fix rate",Math.round(fixed/Math.max(1,r.length)*100)+"%","not market-wide")}
$("#benchmarkForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),r=get("focuseaAnonymousBenchmarks");r.push({tce:N(f.get("tce")),freight:N(f.get("freight")),result:f.get("result"),time:new Date().toISOString()});put("focuseaAnonymousBenchmarks",r.slice(-200));showBench()};
function showCases(){const cases=get("focuseaDecisionCases");$("#savedCases").innerHTML=cases.length?cases.slice(0,8).map((x,i)=>`<article><span>${new Date(x.time).toLocaleString()}</span><b>${esc(x.vessel)}</b><p>${esc(x.route)}</p><strong>${esc(x.decision)} · ${x.risk}/100</strong><small>TCE ${M(x.tce)} · Freight ${x.freight}</small><button type="button" class="ghost" data-remove-case="${i}">Remove</button></article>`).join(""):"<p>No saved case yet. Run a model and save a snapshot to compare decisions.</p>";$$('[data-remove-case]').forEach(b=>b.onclick=()=>{const c=get("focuseaDecisionCases");c.splice(Number(b.dataset.removeCase),1);put("focuseaDecisionCases",c);showCases()})}
$("#saveCase").onclick=()=>{if(!last)return;const v=input(),c=get("focuseaDecisionCases");c.unshift({time:new Date().toISOString(),vessel:v.vessel_name,route:v.route,decision:last.decision,risk:last.risk_score,tce:last.digital_twin.base.tce,freight:v.freight_rate});put("focuseaDecisionCases",c.slice(0,20));showCases()};$("#copyCounter").onclick=async()=>{if(!lastCounter)return;try{await navigator.clipboard.writeText(lastCounter);$("#copyCounter").textContent="Copied";setTimeout(()=>$("#copyCounter").textContent="Copy counter wording",1200)}catch{alert(lastCounter)}};
function dl(name,type,data){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}function report(){return!last?"Run Decision Lab first.":["FOCUSEA DECISION LAB PRO",new Date().toISOString(),"Decision: "+last.decision,"Risk: "+last.risk_score+"/100","Confidence: "+last.confidence+"%","Approval: "+last.approval_status,"Recommended: "+last.recommended_scenario,"Break-even freight: "+last.boundaries.break_even_freight.toFixed(2),"Target freight: "+last.boundaries.required_freight.toFixed(2),"","COUNTER",last.counter,"","STRESS CASES",...last.stress_cases.map(x=>`${x.name}: TCE ${x.tce} / Net ${x.net_profit}`),"","EVIDENCE",...last.evidence_chain.items.map(x=>(x.ready?"[OK] ":"[MISSING] ")+x.document),"","ACTIONS",...last.actions.map(x=>"- "+x),"","AUDIT",JSON.stringify(get("focuseaDecisionApprovals"),null,2),"","Decision support only."].join("\n")}$("#downloadReport").onclick=()=>dl("focusea-decision-pack.txt","text/plain",report());$("#downloadJson").onclick=()=>dl("focusea-decision-pack.json","application/json",JSON.stringify({input:input(),result:last,approvals:get("focuseaDecisionApprovals"),benchmarks:get("focuseaAnonymousBenchmarks")},null,2));showAudit();showBench();showCases();run();
